name: Digger - Drift Detection

on:
  workflow_dispatch:
  schedule:
    - cron: '30 9 * * 1-5' # At 09:30 on every day-of-week from Monday through Friday

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  detect-drift:
    # This disables the entire workflow
    if: false

    runs-on: arc-dsk1-org

    steps:
      - name: Set git config
        run: |
          /usr/bin/git config --global --add url."https://${{ secrets.TFMODULES_GH_PAT_TOKEN }}@github.com/criticalcase".insteadOf https://github.com/criticalcase

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_DIGITAL_API_KEY }}

      - name: digger drift detection
        uses: diggerhq/digger@v0.6.81
        with:
          mode: drift-detection
          no-backend: true
          setup-aws: true
          setup-opentofu: true
          opentofu-version: v1.8.8
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          drift-detection-slack-notification-url: ${{ secrets.MATTERMOST_ALERT_WEBHOOK }}
        env:
          TELEMETRY: false

      - name: Notify mattermost of failure
        if: failure()
        uses: mattermost/action-mattermost-notify@master
        with:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_ALERT_WEBHOOK }}
          MATTERMOST_CHANNEL: ds-alerts
          TEXT: |
            This is a message from ${{ github.repository }}.
            [Digger Drift Detection Action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) has failed execution :x:
          MATTERMOST_USERNAME: ${{ github.triggering_actor }}
          MATTERMOST_ICON_URL: https://cdn3.iconfinder.com/data/icons/system-basic-vol-4-1/20/icon-note-attention-alt3-512.png
